### PR TITLE
happify

### PR DESCRIPTION
**Pull request by Yijia-Zhou**

### CODE REVIEW

**Comment by Yijia-Zhou** [comment]
for sibbay-ai/doc-survey#10

**Comment by Yijia-Zhou** [comment]
for https://github.com/sibbay-ai/doc-survey/issues/12

**Comment by Yijia-Zhou** [comment]
for https://github.com/sibbay-ai/doc-survey/issues/13

**Comment by fushang318** [comment]
1

**Comment by fushang318** [comment]
1

**Pull request merged**
